= Linux scripts
:baseurl: fake/../..
:imagesdir: {baseurl}/../images
:doctype: book
:toc: macro
:toclevels: 5
:idprefix:
:sectanchors:
:sectlinks:
:sectnums:
:last-update-label!:

These shell scripts build the vehicle simulator Rigs of Rods and its dependencies on systems using apt as package manager (e.g. Debian, Ubuntu, Mint).

toc::[]

== Get it
[source, bash]
----
git clone https://github.com/Hiradur/rigsofrods-linuxscripts.git
----

== Build and install

Run these commands from console in this order and not simultaneously:

[source, bash]
----
sh RoRdepsapt.sh
sh RoRdeps.sh
sh RoRcore.sh
sh RoRcontent.sh
----

Notes::
* `RoRdepsapt.sh` will first ask for sudo password and will prompt you a bit later to confirm the installation of the packages. Make sure the packages are not in conflict with something you need (usually does not happen).
* `RoRdeps.sh` and `RoRcore.sh` do not require user interaction.
* `RoRcontent.sh` only requires you to choose the content you want to download in the beginning.
* To change default directories and make parameters edit the config file (optional).
* Depending on your hardware and internet speed this can take quite a while. As long as the scripts are running everything is fine. If an errors occurs they will stop and state the error.

== Update to current snapshot
Simply re-run

[source, bash]
----
sh RoRcore.sh
----

== General notes
* Included is a script for profiling. If you don't know what that means then it is not for you!
* If for whatever reason you copy parts of the script into the console make sure to set configuration variables appropriately, either manually, or by sourcing the config file like this:

[source, bash]
----
. ./config
----

== Links
* https://github.com/Hiradur/rigsofrods-linuxscripts[Git repository]
* http://rigsofrods.com/threads/114853[Forum thread]
