= Compiling on OS X
:baseurl: fake/../..
:imagesdir: {baseurl}/../images
:doctype: book
:toc: macro
:toclevels: 5
:idprefix:
:sectanchors:
:sectlinks:
:sectnums:
:last-update-label!:

toc::[]

== Build script to automatize building process
There is an ongoing effort to create a shell script which fully automatizes the process of building RoR on OS X so even someone with no knowledge of coding could build RoR easily. The script is not finished yet and contributions are greatly appreciated. You can find the script on GitHub: https://github.com/Hiradur/rigsofrods-osxscripts

Features still missing::
* GTK+2.0 installation
* gdk2-pixbuf installation

== Overview
NOTE: These instructions are not entirely up to date and need an experienced Mac user to update.

Rigs of Rods is a complex beast. It has a 3D engine, physics simulator, water and sky plug-ins, input device system, networking, localization plug-in module... and so on.

Rigs of Rods is built in 4 steps::
* Download source code for RoR and supporting libraries (dependencies)
* Compile libraries
* Using CMake, create a Makefile for RoR
* Use make to build the RoR app

== Prerequites
To compile RoR you will have to work with the Terminal (Finder → Go To → Utilities → Terminal).

You need XCode Command Line Tools

[source, bash]
----
xcode-select --install
----

You need the package manager brew to install some dependencies. See http://brew.sh for info. You should install without sudo to minimize risk of damaging your system.

[source, bash]
----
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
----

Once brew is installed install these packages:

[source, bash]
----
brew install wget pkgconfig cmake git boost wxwidgets openal-soft
----

== Additional dependencies not found in brew repositories
You have to compile a number of additional dependencies first to be able to compile RoR. Except for OGRE none of these are required to build RoR but highly recommended (or else you will lack GUI, vegetation, proper sky, multiplayer and scripting).

=== OGRE
==== OGRE dependencies
[source, bash]
----
cd ~/rigs-of-rods/source
wget —c O ogredeps.zip https://bitbucket.org/cabalistic/ogredeps/get/tip.zip
unzip -o ogredeps.zip
cd cabalistic-ogredeps-*
cmake -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING= \
-DCMAKE_INSTALL_PREFIX="~/rigs-of-rods/install" \
-DOGREDEPS_BUILD_CG:BOOL=TRUE \
.
make -j2
make install
----

==== OGRE itself
[source, bash]
----
cd ~/rigs-of-rods/source
wget -c -O ogre.zip http://bitbucket.org/sinbad/ogre/get/v1-8.zip
unzip -o ogre.zip
cd sinbad-ogre-*

# Apply patch for OS X 10.10
wget https://gist.github.com/Hiradur/a5573323ae2701bef6bc/download
patch -p1 < ogre1.8osx.patch

cmake -DCMAKE_INSTALL_PREFIX="~/rigs-of-rods/install" \
-DCMAKE_BUILD_TYPE:STRING=Release \
-DOGRE_STATIC=1 \
-DOGRE_BUILD_SAMPLES:BOOL=OFF .
make -j2
make install
----


[IMPORTANT]
====
After this step the environment variable "PKG_CONFIG_PATH" has always to be set, otherwise CMake will not be able to find OGRE. Do this now and every time you open a new Terminal:

[source, bash]
----
export PKG_CONFIG_PATH="~/rigs-of-rods/install/lib/pkgconfig"
----
====

=== MyGUI
A specific revision is required

[source, bash]
----
cd "~/rigs-of-rods/source"
wget -c -O mygui.zip https://github.com/MyGUI/mygui/archive/a790944c344c686805d074d7fc1d7fc13df98c37.zip
unzip -o mygui.zip
cd mygui-*
cmake -DCMAKE_INSTALL_PREFIX="~/rigs-of-rods/install" \
-DCMAKE_BUILD_TYPE:STRING=Release \
-DMYGUI_BUILD_DEMOS:BOOL=OFF \
-DMYGUI_BUILD_DOCS:BOOL=OFF \
-DMYGUI_BUILD_TEST_APP:BOOL=OFF \
-DMYGUI_BUILD_TOOLS:BOOL=OFF \
-DMYGUI_BUILD_PLUGINS:BOOL=OFF .
make -j2
make install
----


=== OGRE Paged Geometry
[source, bash]
----
cd "~/rigs-of-rods/source"
git clone --depth=1 https://github.com/Hiradur/ogre-paged.git
cd ogre-paged
git pull
cmake -DCMAKE_INSTALL_PREFIX="~/rigs-of-rods/install" \
-DCMAKE_BUILD_TYPE:STRING=Release \
-DPAGEDGEOMETRY_BUILD_SAMPLES:BOOL=OFF .
make -j2
make install
----

=== Caelum
[source, bash]
----
cd "~/rigs-of-rods/source"
wget -c -O caelum.zip http://caelum.googlecode.com/archive/3b0f1afccf5cb75c65d812d0361cce61b0e82e52.zip
unzip -o caelum.zip
cd caelum-*
cmake -DCMAKE_INSTALL_PREFIX="~/rigs-of-rods/install" \
-DCaelum_BUILD_SAMPLES:BOOL=OFF .
make -j2
make install
# important step, so the plugin can load:
ln -sf "~/rigs-of-rods/install/lib/libCaelum.so" "~/rigs-of-rods/install/lib/OGRE/"
----

=== MySocketW
[source, bash]
----
cd "~/rigs-of-rods/source"
git clone --depth=1 https://github.com/Hiradur/mysocketw.git
cd mysocketw
git pull
sed -i '/^PREFIX *=/d' Makefile.conf
make -j2 shared
PREFIX="~/rigs-of-rods/install" make install
----

=== AngelScript
[source, bash]
----
cd "~/rigs-of-rods/source"
mkdir angelscript
cd angelscript
wget -c http://www.angelcode.com/angelscript/sdk/files/angelscript_2.22.1.zip
unzip -o angelscript_*.zip
cd sdk/angelscript/projects/gnuc macosx
sed -i '/^LOCAL *=/d' makefile
# make fails when making the symbolic link, this removes the existing versions
rm -f ../../lib/*
make -j2
rm -f ../../lib/*
LOCAL="~/rigs-of-rods/install" make -s install
----

== Build the game
[source, bash]
----
git clone https://github.com/RigsOfRods/rigs-of-rods.git
cd rigs-of-rods
git pull
cmake -DCMAKE_INSTALL_PREFIX="~/rigs-of-rods/install" \
-DROR_USE_MYGUI="TRUE" \
-DROR_USE_OPENAL="TRUE" \
-DROR_USE_SOCKETW="TRUE" \
-DROR_USE_PAGED="TRUE" \
-DROR_USE_CAELUM="TRUE" \
-DROR_USE_ANGELSCRIPT="TRUE" \
-DCMAKE_BUILD_TYPE=RELEASE \
-DCMAKE_CXX_FLAGS="-O2 -pipe -march=native" \
.
make -j2
sed -i '/^PluginFolder=/d' bin/plugins.cfg
echo "PluginFolder=~/rigs-of-rods/install/lib/OGRE" >>bin/plugins.cfg
cp -R bin "~/rigs-of-rods/install"
----

If your build was successful you will find the binaries to start the game in _~/rigs-of-rods/install/bin_

