---

title: "Test Build 4 released!"

date: "2015-07-19"

firstname: "Moncef"

lastname: "Ben Slimane"

profile: "https://github.com/Max98"

nick: "Max98"

tags:
  - News
  - Development

---
= Test Build 4 released!
:firstname: Moncef
:lastname: Ben Slimane
:profile: https://github.com/Max98
:nick: Max98
:email: {profile}[@{nick}]
:revdate: 19 July 2015
:baseurl: fake/../..
:imagesdir: {baseurl}/../images
:doctype: article
:icons: font
:idprefix:
:sectanchors:
:sectlinks:
:sectnums!:
:skip-front-matter:
:last-update-label!:

Hello there,

The blog post is a bit late but oh well.

We are getting closer and closer to the 0.4.5 release with each test build.

RoR 0.4.5's release is aimed at 11 August, but who knows? It might come a bit later.

Today, Test Build 4 got released!

Changelog::
* Added ability to select skidmarks quality.
* Added flexbody_lods & flexbody_cache_system configs to the ingame options.
* Added some main menu music. (can be disabled via ingame options)
* Improved overall performances.
* Improved Aircraft's GUI
* Improved managed materials. (the ones you use on a truck file, are now just a part of it, wiki page to come)
* Improved reflections (thanks to derbymutt)
* Improved the parser, more fault tolerance
* Removed current PSSM shadows technique, currently not working correctly.
* Fixed TB3's cache bug.
* Fixed nodes2 with flexbodies.
* Fixed crash 'back to menu' on Linux.
* Fixed Hydrax under OpenGL .
* Fixed triggers not extending with commands/commands2.
* Fixed fixes (Nodes who don't move at all)
* Fixed flashing flares.
* Fixed Pause Menu bug where mouse don't move when using free camera.
* Fixed unlimited sight range.
* Fixed wallpapers resolution ratio.
* Fixed meshwheels/meshwheels2 parser bug. (Where the comma wasn't working as intended in the mesh file's name)
* Fixed waves being rendered at wrong height.
* Fixed soundscripts duplicated name makes archive not load.
* Feature: More realistic turbo simulation.
* Feature: AI now can be scripted using Angelscript, wiki page to come.
* Feature: Mods are now sorted by alphabetic order.

A car that uses the new turbo code: http://www.rigsofrods.com/threads/118984-Lotus-76-1-for-current-and-future-ror-versions-(Updated-for-test-build-4)[Lotus-76-1-for-current-and-future-ror-versions-(Updated-for-test-build-4)]

Have fun and don't forget to https://github.com/RigsOfRods/rigs-of-rods/issues[report bugs].

http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev#post1383984[Download here!]
