---

title: "My personal vision for Rigs of Rods"

date: "2015-01-15"

firstname: "Niklas"

lastname: "Kersten"

profile: "https://github.com/Hiradur"

nick: "Hiradur"

tags: ["Development"]

---
= My personal vision for Rigs of Rods
:firstname: Niklas
:lastname: Kersten
:profile: https://github.com/hiradur
:nick: Hiradur
:email: {profile}[@{nick}]
:revdate: 15 January 2015
:baseurl: fake/../..
:imagesdir: {baseurl}/../images
:doctype: article
:icons: font
:idprefix:
:sectanchors:
:sectlinks:
:sectnums!:
:skip-front-matter:
:last-update-label!:

With the blog section now being back alive I though I'd give it a shot and write about my personal goals for Rigs of Rods. Every developer working on an open source project usually has his own vision for what the project could become and works on things that bring it closer to that vision.

== My vision of Rigs of Rods

I would like to see RoR going much faster than it currently does. RoR is usually limited by the CPU as it has to do a lot of floating point math to simulate the behaviour of beams and nodes. Other limiting factors probably are memory latency and bandwidth since structures for beams and nodes are quite large in size and there are hundreds of them per vehicle. Besides the fact that the whole phsyics core could use a cleanup it is also required that we increase accuracy (discussion: link:http://www.rigsofrods.com/threads/118051-Discussion-Moving-to-double-precision-for-physics[Discussion-Moving-to-double-precision-for-physics]) to improve the quality of the simulation. When we do that a major overhaul of the physics core is needed which would be a great chance to improve performance as well. I believe that there is more room for parallelization and that we should use it whenever possible. In the best case RoR should be able to max out any number of CPU cores while still running significantly faster on a single core than it does now.

Besides a speedup in performance I would also like to see the physics calculations being moved to the server. The details are unclear yet because it would suddenly increase server hardware requirements a lot. Maybe we will have an option to toggle serverside physics on and off.
The major benefit of serverside physics calculation is that multiplayer collisions are possible, something that many have asked for and I want to see happening myself. It would also lead to a clear separation between client and server, potentially putting less stress on the client than before. We will have to see how much that could be since some calculations will probably still be needed clientside for movement predicition to reduce perceived lag. It would certainly seperate rendering and physics though, already increasing performance.

I got access to an 80-core cluster computer. My ultimate goal is that the RoR server (with physics calculations being serverside) is able to take advantage of such a system. I would like to see it being able to make use of all cluster nodes using OpenMPI to spread physics calculations across all cores so we can potentially have many people spawning many vehicles in one multiplayer session. In case this becomes possible I may host a community event, hosting a RoR server on said cluster for an evening to have a big wreck fest. It's still uncertain if this is possible at all. The possible degree of parallelization for the physics core has yet to be determined. When working with clusters additional problems arise like latency and bandwidth for communication between nodes. The latency could be large enough to make this whole project fail but since a similar project probably has never been done before we can't know for certain until we tried.

So, to summarize::
* large performance increase
* ability to make use of any number of CPU cores, if possible
* serverside physics calculations
* OpenMPI support for use on clusters

Keep in mind though that this is just a vision of mine yet. Work hasn't even started and it will probably take a while until it does since we would like to provide a solid new stable build first. Some of these things may not even possible or won't ever come to life. We'll have to see what the future holds.
