---

title: "Coming Soon: New Home page and Wiki"

date: "2015-07-07"

firstname: "Artem"

lastname: "Vorotnikov"

profile: "https://github.com/skybon"

nick: "skybon"

---
= Coming Soon: New Home page and Wiki
:firstname: Artem
:lastname: Vorotnikov
:profile: https://github.com/skybon
:nick: skybon
:email: {profile}[@{nick}]
:revdate: 2015-07-07
:baseurl: fake/../..
:imagesdir: {baseurl}/../images
:doctype: article
:icons: font
:idprefix:
:sectanchors:
:sectlinks:
:sectnums!:
:skip-front-matter:
:last-update-label!:

:agpl-uri: http://www.gnu.org/licenses/agpl.html

:github-org: rigsofrods
:site-repo-name: rigsofrods.github.io
:ror-repo-name: rigs-of-rods

:site-repo-uri: https://github.com/{github-org}/{site-repo-name}
:ror-repo-uri: https://github.com/{github-org}/{ror-repo-name}

:site-uri: https://{site-repo-name}
:ru-docs-uri: {site-uri}/ru/docs

:sql-inj: https://www.netsparker.com/blog/web-security/sql-injection-vulnerability-history
:wordpress-vuln: http://www.zdnet.com/article/over-1-million-wordpress-websites-at-risk-from-sql-injection
:drupal-vuln: http://www.bbc.com/news/technology-29846539
:joomla-vuln: http://krebsonsecurity.com/2013/08/simple-hack-threatens-oudated-joomla-sites
:vbulletin-vuln: http://krebsonsecurity.com/2013/10/thousands-of-sites-hacked-via-vbulletin-hole

:atom-uri: https://atom.io
:asciidoctor-uri: http://asciidoctor.org
:webp-enwiki: https://en.wikipedia.org/wiki/WebP

*Dear friends*

My name is *Artem Vorotnikov*, and as some of you know, I have recently joined the RoR development team. Today I am going to talk about the RoR website goodies we have prepared for you this summer.

== About current website
rigsofrods.com is a dynamic website that uses a content management system and several other software packages.

The primary part is of course vBulletin forum CMS. MediaWiki with numerous extensions is used for /wiki subpart. Both of these components share PHP installation and MySQL database, such setup provides account integration between the former two.

In this blog post I am going to describe how CMS work and why we should move away from it.

== Dynamic past
Site authors have always wanted to author and publish content without much hassle.

Back in 2000s we had no swiss army knife browsers with JavaScript, modern CSS, web frameworks et al. So Content Management Systems were conceived. Based on PHP and MySQL, these monsters provide owner with a database engine. All content is stored internally; web page is generated on every single request.

It did its job then, and does today. Adding and modifying content is very easy for both owner and end user. Deployment does not require significant expertise. Simply put, you don't have to fire up an IDE or text editor because all configuration and authoring is done online with neat interface. This is how CMS became dominant in the wild.

Yet they have their own pitfalls. Sometimes nightmares. Read on.

=== Security
The vast majority of content management systems (incl. vBulletin) require a database engine, usually MySQL for data storage. It is faster than plain text files and allows for more end user interactivity.

The latter part comes with a very hefty price. Ever heard of {sql-inj}['SQL injection']? Say, access a specially crafted link and you make the database engine execute the wrong code. It is one of the top online vulnerabilities today. And do you know how this became known to the public? You guessed it. {wordpress-vuln}[Wordpress]. {drupal-vuln}[Drupal]. In short, content management systems.

There're other exploits: {joomla-vuln}[Joomla]. *{vbulletin-vuln}[vBulletin]*. CMS are just too bloated, complex to maintain and therefore buggy.

Speaking of our software, right now I am aware of several 0-day vulnerabilities that could break website database instantly. Pop. Nothing. Error 403 or 404 instead of years of RoR history.

=== Upkeep
As I have already mentioned dynamic websites require a database engine, usually MySQL. Not every hosting service can provide you with that.

And even if they do, you need to do maintenance work regularly, update. This consumes our precious time we could spend on improving the game itself.

=== Flexibility
Clothes make the man. If you manage to catch the eye of a potential user, you have the following, if you don't then my condolences.

To do that on the Internet one must have a modern, nice looking, professionally done and informative home page. It is that very thing tells the players basic 80% about the game. And unless it stands out from the crowd of thousands of such 'home's your average web surfer will skip it to never return.

What do we have today? A wall of text that really looks like a long forum post. A huge paragraph. Then another one. And another. Then a bullet list. Afterwards a video. And... that's it.

Nothing strange as the whole website is based on forum software. It may be robust and flexible as a forum, true, but really, really not as anything else. Not as home, not even as a blog.

Home page is almost always custom made, hand-crafted by web designer. This is exactly what CMS are *not* able to provide.

''''
This is unacceptable so it's time to move on. Here's what awaits you.

== Everything old is new again
Back in 1990s all websites were coded by hand. Yes, fire up the text editor and type, type, type.

Handcrafted website creation has never been easier than today, in 2015. Now we have rapid templating, light markup and website generators. There is no need for huge databases for most of the tasks anymore.

So, behold, the {site-uri}[new home page]

=== 100% static
No databases, no CMS. All content is created once at build time. Hence the site is *fast*, *secure* and *flexible*. JavaScript and browser features are used where we need interactivity.

=== The look of 2015
This home page actually stands out and catches the visitor's eye.

=== New Wiki
And yes, we have a new wiki (called 'docs').

No more MediaWiki, no more databases. Pages are stored in plain text and may be easily edited in Notepad (although I recommend {atom-uri}[Atom], hehe ;-) ).

Docs use {asciidoctor-uri}[AsciiDoc] for markup now. The preferred image format is {webp-enwiki}[WebP] (it's open and has better compression than JPEG and PNG).

=== First-class localization
Да. Ja. Oui.

The new website is multilingual. Just try visiting the {site-uri}[root of the site]. If your browser language matches one of available locales, you'll be redirected. Otherwise you can choose the language yourself.

Most importantly, all content is *kept in sync*. All translations are directly based on English source articles. Even if some parts are added, foreign visitors will still be able to read them untranslated.

Feel free to help with translation, you can find instructions here.

The new documentation is *also fully localizable*, just see the Russian example {ru-docs-uri}[here].

=== Streamlined workflow
The new website is developed with git software and {site-repo-uri}[hosted on GitHub]. This corresponds with Rigs of Rods main development which also {ror-repo-uri}[occurs on GitHub]. Therefore if you wish to report bugs or fix stuff yourself - you can do it the same way as for RoR itself.

=== Free and open source
In line with the project spirit the new website code is open source under the {agpl-uri}[GNU Affero General Public License v3]. You can always tinker with it, see how it works for yourself.

== About the forums
vBulletin forum has served us well so far and there're no immediate deprecation plans. It will be moved to _forum.rigsofrods.com_, however.

== All hands on deck
What you see is a developer preview right now. We need all the help we can get for porting content, weeding out bugs. Please visit our {site-repo-uri}[GitHub repository page] for more information

Thank you for reading, I hope you enjoy our work.
