= Download
:baseurl: fake/../..
:imagesdir: {baseurl}/../images
:doctype: book
:idprefix:
:toc: right
:toclevels: 5
:last-update-label!:

== Windows

* Download the latest stable release link:http://sourceforge.net/projects/rigsofrods/files/rigsofrods/0.38/RoR-Setup-0.38.67.exe[here] (recommended)
* Preview builds for upcoming versions may be found link:http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev[here]
* If you want to build from source see <<{baseurl}/docs/compile-windows/index.adoc#,Compiling on Windows>>

== Linux

* Packages for various distributions: link:http://www.rigsofrods.com/threads/113517-Collection-of-prepuilt-packages-for-various-Linux-distributions[here]
* Build from source, see <<{baseurl}/docs/compile-linux/index.adoc#,Compiling on Linux>> (recommended, see tip at the beginning of the page if you are lazy)

== OS X

Unfortunately, due to lack of OS X coders, there is no up to date build of the latest version available.

* If you want to build from source see <<{baseurl}/docs/compile-osx/index.adoc#,Compiling on OS X>>

=== Overview / Readme / FAQ

You can find more information about the latest stable release here: <<release-notes/0.38/index.adoc#,Gaggenau>>

The changelog is presented <<changelog/index.adoc#,here>>.

Many questions are answered in the documentation, have a look around: <<{baseurl}/docs/index.adoc#,Documentation index>>

=== License

Rigs of Rods is free and open source software under the GPL v3 license, meaning it is both free as in speech (you can modify it) and free as in beer (it does not cost you anything).

=== Legacy

If you are interested in Rigs of Rods' history check out the museum link:http://sourceforge.net/projects/rigsofrods/files/rigsofrods/museum/[here]
