---

title: "Test Build 5 released!"

date: "2015-08-04"

firstname: "Moncef"

lastname: "Ben Slimane"

profile: "https://github.com/Max98"

nick: "Max98"

tags: ["News", "Development"]

---
= Test Build 5 released!
:firstname: Moncef
:lastname: Ben Slimane
:profile: https://github.com/Max98
:nick: Max98
:email: {profile}[@{nick}]
:revdate: 2015-08-04
:baseurl: fake/../..
:imagesdir: {baseurl}/../images
:doctype: article
:icons: font
:idprefix:
:sectanchors:
:sectlinks:
:sectnums!:
:skip-front-matter:
:last-update-label!:

Key highlights::
* Added some new wallpapers.
* Improved the parser, even more fault tolerance.
* Fixed PSSM shadows. (Not perfect but much better than before)
* Fixed Flares that could be activated in Pause Menu.
* Fixed beam material using set_beam_defaults.
* Fixed bug where beams couldn't be connect to wheel nodes.
* Fixed camera views glitch when switching cars.
* Fixed crash when removing car in cabin camera.
* Fixed creak sounds.
* Feature: Turbo Wastegate and anti-lag simulation. (Sounds need some improvements)

This build is now the closest result to what is coming with the release of the 11 August. This is also a Beta build. 

Known Issues::
* Trains may still randomly crash when going over a switch if inter-vehicle collision is enabled.
* Shadows are very FPS-yummy and sometimes conflict with terrain's layers. (E.g.: Auriga, Greece.)
* Back to menu is not very stable yet.
* Skidmarks have some memory leaks.
* Ingame mapping not working yet.


Documentation about how to add shadows to your models/vehicles will be coming soon, for the moment, only in-truck-file managed-materials support shadows and self-shadowing.

How to download:

From now on, Rigs of Rods can be updated automatically by a special utility. Download the updater from http://www.rigsofrods.com/threads/120032-Testing-Purposes-Updater-V2[here].
Just put it in any version of the game and it will upgrade Rigs of Rods to the latest release.
You can also use the https://yadi.sk/d/OOKjBVzmiJzxs[zip archive].

This might be the last archived release though, since it is possible to use the updater given with the build.

image::http://www.rigsofrods.com/attachment.php?attachmentid=538326&d=1438687476[role=""]
