---
title: "Compiling on Linux"
---
:baseurl: fake/../..
:imagesdir: {baseurl}/../images
:doctype: book
:toc: right
:toclevels: 5
:idprefix:
:sectanchors:
:sectlinks:
:sectnums:
:last-update-label!:

If you just want to install RoR without much hassle then have a look at these shell scripts, they bundle all necessary steps:
link:http://rigsofrods.com/threads/114853-Install-scripts-for-latest-snapshot-for-Debian-Ubuntu-Mint[Ubuntu/Debian/Mint]

Ready made packages for various Linux distributions are available link:http://rigsofrods.com/threads/113517-Collection-of-prepuilt-packages-for-various-Linux-distributions[here].

== Getting the required build dependencies

=== Installing required packages usually found in repositories

==== Ubuntu
[source,bash]
----
sudo apt update
sudo apt install subversion mercurial git automake cmake build-essential pkg-config doxygen libfreetype6-dev libfreeimage-dev libzzip-dev scons libcurl4-openssl-dev nvidia-cg-toolkit libgl1-mesa-dev libxrandr-dev libx11-dev libxt-dev libxaw7-dev libglu1-mesa-dev libxxf86vm-dev uuid-dev libuuid1 libgtk2.0-dev libboost-all-dev libopenal-dev libois-dev libssl-dev libwxgtk3.0-dev
----

==== Gentoo
[source,bash]
----
mkdir /etc/portage
echo "media-libs/freeimage ~x86" >> /etc/portage/package.keywords
echo "media-libs/freeimage" >> /etc/portage/package.unmask
emerge -av cmake devil boost nvidia-cg-toolkit subversion wxGTK freeimage zziplib
eselect wxwidgets set 1
----

== Compiling and installing missing packages
You have to install all software which is not available in your distributions' repository by hand. This is necessary to fulfill the required dependencies.

*Please note*: OGRE shipped with some distributions does not have support for Cg enabled which is needed for Rigs of Rods (otherwise shaders will be missing, e.g. completely white cars) which is why you should compile it yourself.

== Downloading the source code
[source,bash]
----
git clone https://github.com/RigsOfRods/rigs-of-rods.git
cd rigs-of-rods
----

== Configuring the source code
There are two different ways to configure your RoR build, either via Command Line Interface (aka CLI) or via GUI interface. CLI is the most straight forward. If you are only interested in compiling standard RoR, this is the recommended method.

=== CLI
[source,bash]
----
cmake -DROR_USE_MYGUI="TRUE" \
-DROR_USE_OPENAL="TRUE" \
-DROR_USE_SOCKETW="TRUE" \
-DROR_USE_PAGED="TRUE" \
-DROR_USE_CAELUM="TRUE" \
-DROR_USE_ANGELSCRIPT="TRUE" \
-DCMAKE_BUILD_TYPE=RELEASE \
.
----

=== GUI

The cmake GUI might not be provided on all in systems.
To start the cmake gui run `cmake-gui .`

* press `Configure`
* select `Unix Makefiles` and `Use default native compilers` (that are the default options) and press `Finish`
* press `Configure` again until all list entries are white
* look at the log window for information and errors (look for red lines with " &gt; " in front)
* enable the components you want to compile in: ROR_*
* press `Configure` again until the `Generate` button is click-able
* press `Generate`
* close cmake-gui

== Building the source code
To start building simply run `make`

NOTE: You can speed up compilation by making use of multithreading. Just add a -j**x** flag where *x* is the number of simultaneous build jobs you want (basic rule: one job per cpu core).

== Updating existing sources

If you already got the sources and just want to update, follow the steps below:
[source,bash]
----
cd rigs-of-rods
git pull

rm -f CMakeCache.txt
rm -rf CmakeFiles/
cmake-gui .

make
----
