= RoR.cfg
:baseurl: fake/../..
:imagesdir: {baseurl}/../images
:doctype: book
:toc: macro
:toclevels: 5
:idprefix:
:sectanchors:
:sectlinks:
:sectnums:
:last-update-label!:

This file sets options for RoR. Most of them can be configured using the configurator, but some cannot.

toc::[]

== File Format
File format in general represents a set of https://en.wikipedia.org/wiki/Attribute%E2%80%93value_pair[attribute-value pairs] like:

[source]
----
<attribute>=<value>
----

For example: `Motion blur=Yes`

== Configuration Values
=== Graphics
==== Texture Filtering
Texture filtering that will be used ingame::
* Bilinear
* Trilinear
* Anisotropic (best looking)

==== Sky effects
Type of sky that will be loaded::
* Sandstorm (fastest)
* Caelum (best looking, slower)

==== Shadow technique
Shadow technique to be used ingame::
* None
* Texture shadows
* Parallel-split Shadow Maps

==== Water effects
Type of water to use::
* Basic (fastest)
* Reflection
* Reflection + refraction (speed optimized)
* Reflection + refraction (quality optimized)
* Hydrax

==== Waves
Adds a lot of fun in boats::
* Yes
* No

==== Vegetation
How much grass and how many trees there will be::
* None (fastest)
* 20%
* 50%
* Full (best looking, slower)

==== Motion blur
Enables the motion blur effect::
* Yes
* No

==== Sunburn
Bluish blinding effect::
* Yes
* No

==== Mirrors
Enable rear view mirrors in cabin view::
* Yes
* No

=== Controls
==== Force Feedbac
* Enable
* Disable

==== Deadzone
* Decimal between 0 and 0.5 (0.1 = 10%, 0.5 = 50%, default: 0.1)

=== Advanced
==== Lights
* None (fastest)
* No light sources
* Only current vehicle, main lights
* All vehicles, main lights
* All vehicles, all lights

=== Debug
==== Input Grab
Determines how RoR controls mouse input
* *All* - always grabs the mouse, cannot leave the screen (alt+tab)
* *Dynamically* - grabs the mouse while the window is in focus, can leave screen (alt+tab)
* *None*

=== Network
==== Network enable
* Yes
* No

==== Server port
* Integer value

==== Server name
* String

==== Nickname
* String

== Abstracted by the configurator
* "Caelum Fog Density", possible Values: 0.05-0.000001 (how dense the fog with Caelum sky is, default: 0.005)
* "Sandstorm Fog Start", possible Values: 100-10000 (where the fog with Sandstorm starts, default: 500)

== Sample
A RoR.cfg with lowest settings:

[source]
----
Texture Filtering=None (fastest)
Sky effects=Sandstorm (fastest)
Shadow technique=No shadows (fastest)
Water effects=None
Waves=No
Engine smoke=No
Dust=No
Spray=No
Custom Particles=No
Dashboard=No
Mirrors=No
Sunburn=No
Bloom=No
Motion blur=No
3D Sound renderer=No sound
Threads=1 (Standard CPU)
Enhanced wheels=No
FarClip Distance=100
Fog=No
Lights=None (fastest)
Vegetation=None (fastest)
Screenshot Format=jpg (smaller, default)
Network enable=No
----

